name: docs_pages_workflow

# Execute this workflow automatically when pushing to the main branch
on:
  push:
    branches: [ main ]

jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install -U sphinx
          python -m pip install myst_parser
          python -m pip install sphinx-book-theme

      - name: Build the Sphinx documentation
        run: |
          make -C docs clean
          make -C docs html

      - name: Init new repo in dist folder and commit generated files
        run: |
          cd docs/_build/html/
          git init
          touch .nojekyll  # Prevents GitHub Pages from processing the site with Jekyll
          git add -A
          git config --local user.email "youxiang.dong@outlook.com"
          git config --local user.name "Dong237"
          git commit -m 'deploy'

      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          directory: ./docs/_build/html

# https://www.youtube.com/watch?v=SxkM1SK9YlI
